//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagementSystem.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamedOrder
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<int> ServiceCount { get; set; }
    }
}
